name: Deploy contabil-progresso-desafios

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      service-name: contabil-progresso-desafios
      deployment-name: contabil-progresso-desafios-deployment
      port: "10096"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
